# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-EN-WSD-CorpusBased
version:      0.11
version_from: lib/Lingua/EN/WSD/CorpusBased.pm
installdirs:  site
requires:
    String::Util:                  0.11
    WordNet::QueryData:            1.4
    WordNet::Similarity:           1.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
